/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String APP_NAME = 'talabatee';
  static const String APP_VERSION = '1.5.0+1';
  static const String APP_LOGO = 'assets/images/logo.png';
  static const String PRODUCT_PATH = 'assets/images/products/';

}
